fos_rest:
  serializer:
    serialize_null: true
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  view:
    view_response_listener:  true
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
