security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory: { memory: null }
    user_db_provider:
      entity:
        class: App\Entity\User
        property: apiToken
  firewalls:
    api_admin:
      pattern: ^/api/admin/
      guard:
        authenticators:
          - App\Security\TokenAuthenticator
      provider: user_db_provider
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
